todolist/authapp/urls.py
from django.urls import path


import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

todolist/mainapp/urls.py
from django.urls import path
from .views import add_task, index
from .views import by_category

urlpatterns = [
    path('<int:category_id>/', by_category),
    path('', index, name='index'),
]

todolist/todolist/urls.py
from mainapp.views import add_task, delete_task, add_category, filter_category, delete_category, complite_task
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('add/', add_task, name='add_task'),
    path('delete_task/<int:id>/', delete_task, name='delete_task'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('register/', include('authapp.urls')),
    path('add_category/', add_category, name='add_category'),
    path('filter_category/<slug:category_name>/', filter_category, name='filter_category'),
    path('delete_category/<int:id>/', delete_category, name='delete_category'),
    path('complite_task/<int:id>/', complite_task, name='complite_task'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todolist/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class TaskUser(AbstractUser):
    ava = models.ImageField(upload_to='media', blank=True)
    

todolist/mainapp/models.py
from django.db import models
from authapp.models import TaskUser


class Utask(models.Model):
    title = models.CharField(max_length=100, verbose_name='Task')
    date_create = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date_create')
    date_update = models.DateTimeField(auto_now=True, verbose_name='Date_update')
    achievement = models.BooleanField(default=False, blank=True, verbose_name='achevement')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, blank=True, default='Home', verbose_name='Category')
    author = models.ForeignKey(TaskUser, related_name="tasks", on_delete=models.CASCADE, verbose_name='User')

    def __str__(self) -> str:
        return self.title[:5]

    class Meta:
        verbose_name_plural = 'Tasks'
        verbose_name = 'Task'
        ordering = ['-date_create']


class Category(models.Model):
    category_name = models.CharField(max_length=30, db_index=True, verbose_name='Category', default='Home')
    
    def __str__(self) -> str:
        return self.category_name

    class Meta:
        verbose_name_plural = 'Categories'
        verbose_name = 'Category'
        ordering = ['category_name']

todolist/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from .models import TaskUser

class TaskUserLoginForm(AuthenticationForm):
    class Meta:
        model = TaskUser
        fields = ('username', 'password')

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in self.fields.items():
                field.widget.attrs['class'] = 'form-control'
                field.help_text = ''
                field.label = ''
                field.errors = ''
            

class TaskUserRegisterForm(UserCreationForm):
    class Meta:
        model = TaskUser
        fields = ('username', 'password1', 'password2', 'email', 'ava')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    

todolist/mainapp/forms.py
from django.forms import ModelForm, fields

from .models import Utask

class UtaskForm(ModelForm):
    class Meta:
        model = Utask
        fields = ('title', 'category')

todolist/authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from authapp.forms import TaskUserLoginForm, TaskUserRegisterForm
from django.contrib import auth
from django.urls import reverse

def login(request):
    title = 'Join in'
    login_form = TaskUserLoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('index'))

    content = {'title': title, 'login_form':login_form}
    return render(request, 'authapp/login.html', content)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))     


def register(request):
    title = 'Регистрация'

    if request.method == 'POST':
        register_form = TaskUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = TaskUserRegisterForm()

    content = {'title': title, 'register_form': register_form}

    return render(request, 'authapp/register.html', content)
    
    
def edit(request):
    return HttpResponseRedirect(reverse('index'))


# Create your views here.

todolist/mainapp/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from mainapp.models import Utask, Category
from authapp.models import TaskUser




def index(request):
    task_list = []
    category_list = []
    if request.user.is_authenticated:
        task_list = request.user.tasks.all()
        category_list = Category.objects.all()
        

    return render(request, 'mainapp/index.html', {'task_list': task_list, 'category_list': category_list})

def by_category(request):
    pass

def add_task(request):
    category_list = Category.objects.all()
    if not category_list:
        Category.objects.create(category_name='Home')
        category_list = Category.objects.all()
    if request.method == 'POST':
        Utask.objects.create(title=request.POST.get('title'), author=request.user,
                             category=Category.objects.get(category_name=request.POST.get('cat.category_name')))
        
        return redirect(index)
    else:
        return render(request,'mainapp/add.html', {'category_list': category_list})

def delete_task(request, id):
    task = Utask.objects.get(id=id)
    task.delete()
    return redirect(index)


def add_category(request):

    category_list = Category.objects.all()
    if not category_list:
        Category.objects.create(category_name='Home')
        category_list = Category.objects.all()
    if request.method == 'POST':
        Category.objects.create(category_name=request.POST.get('categoryname'))
        
        return redirect(index)
    else:
        return render(request,'mainapp/add_category.html', {'category_list': category_list})

def filter_category(request, category_name):
    
    category_name = Category.objects.get(category_name=category_name)
    category_list = []
    if request.user.is_authenticated:
        task_list = request.user.tasks.filter(category__category_name=category_name)
        category_list = Category.objects.all()
    return render(request, 'mainapp/index.html', {'task_list': task_list, 'category_list': category_list})


def delete_category(request, id):
    category = Category.objects.get(id=id)
    category.delete()
    return redirect(index)


def complite_task(request, id):
    task = Utask.objects.get(id=id)
    if task.achievement == False:
        task.achievement = True
    else:
        task.achievement = False
    task.save()

    return redirect(index)

todolist/authapp/templates/authapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- Bootstrap JS + Popper JS -->
    <script defer src="{% static 'bootstrap.bundle.min.js' %}"></script>
    <title>ToDo</title>
</head>
<body>
    <div class="container-xl">
        <header class="header">
            <div class="row">
                <div class="col">
                    <span class="header_text">ToDo List</span>
                    <span class="header_text">Nothing is real if you don't believe in who you are</span>
                </div>
            </div>
        </header>
        <main class="write_wrap">
            {% block taskList %}
            {% endblock %}
        </main>
        <footer class="footer">
            <div class="row">
                <div class="col">
                    <span class="header_text">ToDo List</span>
                    <span class="header_text">Nothing is real if you don't believe in who you are</span>
                </div>
            </div>
        </footer>
    </div>
</body>
</html>

todolist/authapp/templates/authapp/login.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block taskList %}
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ login_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Join in">
    </form>
   
{% endblock %}
 

todolist/authapp/templates/authapp/register.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block taskList %}
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ register_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="зарегистрироваться">
    </form>
   
{% endblock %}
 

todolist/mainapp/templates/mainapp/add.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block taskList %}
    
    <form method="POST" action="" class="row">
        {% csrf_token %}
        <div class="col">
            <label for="exampleInputEmail1" class="form-label">Input task</label>
            <input type="text" name="title" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            <div id="emailHelp" class="form-text">Choose category</div>
        </div>
        <select class="form-select" name="cat.category_name" aria-label="Default select example">
            <option selected>{{ category_list.0.category_name }}</option>
            {% for cat in category_list %}
                {% if cat.category_name != category_list.0.category_name %}
                <option value="{{ cat.category_name }}">{{ cat.category_name }}</option>
                {% endif %}
            {% endfor %}
        </select>
        <button type="submit" class="btn btn-primary col-2 my-3">Submit</button>
    </form>
{% endblock %}

todolist/mainapp/templates/mainapp/add_category.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block taskList %}
    
    <form method="POST" action="" class="row add-cat-form">
        {% csrf_token %}
        <div class="col">
            <label for="exampleInputEmail1" class="form-label">Input category</label>
            <input type="text" name="categoryname" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            <div id="emailHelp" class="form-text"></div>
        </div>
        <button type="submit" class="btn btn-primary col-2 my-3">Submit</button>
    </form>
{% endblock %}

todolist/mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- Bootstrap JS + Popper JS -->
    <script defer src="{% static 'bootstrap.bundle.min.js' %}"></script>
    <title>ToDo</title>
</head>
<body>
    <div class="container-xl">
        <header class="header">
            <div class="row justify-content-center">
                <div class="col-12 mb-3">
                    <span class="header_text">ToDo List</span>
                    <span class="header_text">Nothing is real if you don't believe in who you are</span>
                </div>
                {% if user.is_authenticated %}
                    <div class="col-3">
                        <a href="{% url 'auth:edit' %}" class="badge rounded-pill login-link">
                            {{ user.username|default:'Пользователь' }}          
                        </a>
                    </div>
                    {% if user.ava %}
                        <img src="/media/{{ user.ava }}" width="100" height="100" alt="" class="user-ava col-auto">
                    {% endif %}
                {% endif %}  
                
                {% if user.is_authenticated %}
                <div class="col-3">
                    <a href="{% url 'auth:logout' %}" class="badge rounded-pill login-link">выйти</a>
                </div>
                {% else %}
                <div class="col-3">
                    <a href="{% url 'auth:login' %}" class="badge rounded-pill login-link">войти</a>
                </div>
                <div class="col-3">
                    <a href="{% url 'auth:register' %}" class="badge rounded-pill login-link">регистрация</a>
                </div>
                {% endif %}
                
            </div>
        </header>
        <main class="write_wrap">

            {% block taskList %}
            {% endblock %}
        </main>
        <footer class="footer">
            <div class="row">
                <div class="col">
                    <span class="header_text">ToDo List</span>
                    <span class="header_text">Nothing is real if you don't believe in who you are</span>
                    <span class="header_text footer_info">Made by Alexander Dudkov &copy;</span>
                </div>
            </div>
        </footer>
    </div>
</body>
</html>

todolist/mainapp/templates/mainapp/create.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block taskList %}
    <div class="row justify-content-center">
        <div class="col add_form_wrap">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Add Task">
            </form>
        </div>
    </div>

{% endblock %}

todolist/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block taskList %}
    <a href="{% url 'add_task' %}" class="col-2 btn-lg badge rounded-pill login-link">
                    Add Write

    </a>

    <div class="row">
        <div class="col-md-10">
            {% for task in task_list %}
            <div class="row">
                <div class="col border-left border-bottom border-primary cat_blue">
                    
                    
                    {% if task.achievement == True %}
                        <a href="complite_task/{{ task.id }}" class="link-primary done-link mx-3" id="{{ task.id }}">Back</a>
                        <span class="form-check-label text-decoration-line-through">
                            {{ task.title }}
                        </span>
                    {% else %}
                        <a href="complite_task/{{ task.id }}" class="link-primary done-link mx-3" id="{{ task.id }}">Done</a>
                        <span class="form-check-label">
                            {{ task.title }}
                        </span>
                    {% endif %}
                    
                </div>
                <div class="col-1 cat_wrap">
                    <span class="cat_name">
                        {{ task.category }}
                    </span>
                </div>
                <div class="col-1 border-right border-bottom border-primary cat_blue_right">
                    <button type="button" class="close" aria-label="Close">
                        <a href="delete_task/{{ task.id }}"><span aria-hidden="true">&times;</span></a>
                    </button>
                </div>
            </div>
            {% endfor %}       
        </div>
        <div class="col-md-2">
            <nav class="nav nav-fill nav-cat">
            {% for cat in category_list %}
                <div class="mx-3 nav-item-wrap nav-link border-bottom border-primary">
                    <a class="nav-cat-item" href="{% url 'filter_category' cat.category_name %}" name="catname">{{ cat.category_name }}</a> 
                    <button type="button" class="close" aria-label="Close">
                        <a href="delete_category/{{ cat.id }}" class=""><span aria-hidden="true">&times;</span></a>
                    </button>
                </div>
            {% endfor %}
                <a class="mx-3 nav-link nav-cat-item border-bottom border-primary" href="{% url 'index' %}" name="catname">All</a>
                <a href="{% url 'add_category' %}" class="cat-add-link"><span class="nav-link col-2 btn-lg badge rounded-pill login-link">Add Category</span></a>
            </nav>
        </div>  
    </div>
    
{% endblock %}